name: YAML Linting

on:
  pull_request:
env:
  main: ${{ github.base_ref }}
  pr: ${{ github.head_ref }}
  url_pr: ${{ github.event.pull_request.html_url }}
  url_main: ${{ github.event.repository.url }}

jobs:
  lint:
    name: Lint YAML Files
    runs-on: ubuntu-latest

    steps:
      - name: Lint YAML files
        run: |
            find . -type f \( -name "*.yml" -o -name "*.yaml" \) | while read filename; do
              yamllint "$filename"
              echo The files $filename
            done
            echo main br: $main
            echo pr br: $pr
            echo main_url: $url_main
            echo url_pr: $url_pr

  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... other steps to deploy the code
      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: url
            })
